# -*- coding: utf-8 -*-
"""merged_spark_notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SdwaDyZZbCoZ_SMBiczrG9kagaz-7yJ5

# Regression & Classification with Apache Spark MLlib

**Dataset**: E-commerce event log with columns: `event_type`, `product_id`, `brand`, `price`, `user_id`, `user_session`, `product_name`, `category`, `hour`, `day`, `month`, `year`

## Tasks
| Task | Type | Target | Algorithm |
|------|------|--------|-----------|
| Predict product **price** | Regression | `price` (continuous) | Linear Regression |
| Predict **event type** (purchase vs cart) | Classification | `event_type` (binary) | Logistic Regression |

## Pipeline
1. Spark Session
2. Load & Explore
3. Feature Engineering
4. **Regression** — predict `price` (Linear Regression)
5. **Classification** — predict `event_type` (Logistic Regression)
6. Evaluation & Visualizations
"""

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import *
from pyspark.ml.feature import (
    StringIndexer, OneHotEncoder, VectorAssembler,
    StandardScaler
)
from pyspark.ml import Pipeline
from pyspark.ml.regression import LinearRegression
from pyspark.ml.classification import LogisticRegression
from pyspark.ml.evaluation import (
    RegressionEvaluator, BinaryClassificationEvaluator, MulticlassClassificationEvaluator
)

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
spark = SparkSession.builder \
    .appName("Regression_Classification_Ecommerce") \
    .config("spark.sql.shuffle.partitions", "8") \
    .config("spark.driver.memory", "4g") \
    .getOrCreate()

spark.sparkContext.setLogLevel("WARN")

DATA_PATH = "part-00000-592294fe-0de3-464a-b8ed-3c5026285aa9-c000.csv"

df = spark.read.csv(DATA_PATH, header=True, inferSchema=True)
print(f"Rows    : {df.count():,}")
print(f"Columns : {df.columns}")
df.printSchema()

df.show(5)
df.select("price", "hour", "day", "month").describe().show()
print("\n=== event_type distribution ===")
df.groupBy("event_type").count().show()

print("\n=== Top categories ===")
df.groupBy("category").count().orderBy(F.desc("count")).show(10)

print("\n=== Top brands ===")
df.groupBy("brand").count().orderBy(F.desc("count")).show(10)

"""## 3. Feature Engineering (Shared)

Both models share the same feature set. We encode categorical columns (`brand`, `category`, `event_type`) using **StringIndexer → OneHotEncoder**, then assemble all features into a single vector.
"""

data = df.select(
    "event_type", "price", "brand", "category", "hour", "day", "month"
).dropna()

print(f"Rows after dropping nulls: {data.count():,}")

# StringIndexer: converts string labels to numeric indices
brand_indexer    = StringIndexer(inputCol="brand",    outputCol="brand_idx",    handleInvalid="keep")
category_indexer = StringIndexer(inputCol="category", outputCol="category_idx", handleInvalid="keep")
event_indexer    = StringIndexer(inputCol="event_type",outputCol="label",        handleInvalid="keep")
# OneHotEncoder: converts indices to binary vectors
encoder = OneHotEncoder(
    inputCols=["brand_idx", "category_idx"],
    outputCols=["brand_vec", "category_vec"]
)

feature_cols = ["brand_vec", "category_vec", "hour", "day", "month"]

assembler = VectorAssembler(
    inputCols=feature_cols,
    outputCol="features_raw"
)

scaler = StandardScaler(
    inputCol="features_raw",
    outputCol="features",
    withStd=True,
    withMean=False
)

preprocessing = Pipeline(stages=[
    brand_indexer,
    category_indexer,
    event_indexer,
    encoder,
    assembler,
    scaler
])

preprocessor = preprocessing.fit(data)
prepared     = preprocessor.transform(data)

print("Preprocessing done. Sample output:")
prepared.select("event_type", "label", "price", "features").show(5, truncate=True)

"""---
## 4. REGRESSION — Predict `price`

**Target**: `price` (continuous)  
**Features**: brand, category, hour, day, month  
**Model**: Linear Regression  
**Metrics**: RMSE, MAE, R²

"""

# Train / Test split
reg_data = prepared.select("features", "price").withColumnRenamed("price", "label")

reg_train, reg_test = reg_data.randomSplit([0.8, 0.2], seed=42)
print(f"Regression — Train: {reg_train.count():,}  |  Test: {reg_test.count():,}")

lr = LinearRegression(
    featuresCol="features",
    labelCol="label",
    maxIter=20,
    regParam=0.1,
    elasticNetParam=0
)

lr_model = lr.fit(reg_train)

# Training summary
lr_summary = lr_model.summary
print(f"Linear Regression — Training RMSE : {lr_summary.rootMeanSquaredError:.4f}")
print(f"Linear Regression — Training R²   : {lr_summary.r2:.4f}")
print(f"Intercept : {lr_model.intercept:.4f}")

# Evaluate
lr_preds = lr_model.transform(reg_test)

reg_evaluator_rmse = RegressionEvaluator(labelCol="label", predictionCol="prediction", metricName="rmse")
reg_evaluator_mae  = RegressionEvaluator(labelCol="label", predictionCol="prediction", metricName="mae")
reg_evaluator_r2   = RegressionEvaluator(labelCol="label", predictionCol="prediction", metricName="r2")

lr_rmse = reg_evaluator_rmse.evaluate(lr_preds)
lr_mae  = reg_evaluator_mae.evaluate(lr_preds)
lr_r2   = reg_evaluator_r2.evaluate(lr_preds)

print("\n=== Linear Regression — Test Set Results ===")
print(f"  RMSE : {lr_rmse:.4f}")
print(f"  MAE  : {lr_mae:.4f}")
print(f"  R²   : {lr_r2:.4f}")

lr_preds.select("label", "prediction").show(10)

"""---
## 5. CLASSIFICATION — Predict `event_type` (purchase vs cart)

**Target**: `event_type` → binary label (0 = cart, 1 = purchase)  
**Features**: brand, category, price, hour, day, month  
**Model**: Logistic Regression  
**Metrics**: Accuracy, Precision, Recall, F1, AUC-ROC

"""

assembler_clf = VectorAssembler(
    inputCols=["brand_vec", "category_vec", "price", "hour", "day", "month"],
    outputCol="features_raw_clf"
)
scaler_clf = StandardScaler(
    inputCol="features_raw_clf",
    outputCol="features_clf",
    withStd=True,
    withMean=False
)

# Filter  binary classification (
binary_clf_data = prepared.filter(F.col("event_type").isin("purchase", "cart"))

binary_label_indexer = StringIndexer(inputCol="event_type", outputCol="binary_label", handleInvalid="error")
binary_clf_data = binary_label_indexer.fit(binary_clf_data).transform(binary_clf_data)
clf_prep = Pipeline(stages=[assembler_clf, scaler_clf]).fit(binary_clf_data)
clf_data = clf_prep.transform(binary_clf_data).select("features_clf", "binary_label")
clf_data = clf_data.withColumnRenamed("features_clf", "features").withColumnRenamed("binary_label", "label")

clf_train, clf_test = clf_data.randomSplit([0.8, 0.2], seed=42)
print(f"Classification — Train: {clf_train.count():,}  |  Test: {clf_test.count():,}")

print("\nClass distribution in training set:")
clf_train.groupBy("label").count().show()

"""###Logistic Regression

"""

log_reg = LogisticRegression(
    featuresCol="features",
    labelCol="label",
    maxIter=20,
    regParam=0.1,
    elasticNetParam=0,

)

log_reg_model = log_reg.fit(clf_train)

# Training summary
lr_clf_summary = log_reg_model.summary
print(f"Logistic Regression — Training Accuracy : {lr_clf_summary.accuracy:.4f}")
print(f"Logistic Regression — Training AUC-ROC  : {lr_clf_summary.areaUnderROC:.4f}")

# Evaluate on test set
log_reg_preds = log_reg_model.transform(clf_test)

bin_evaluator   = BinaryClassificationEvaluator(labelCol="label", rawPredictionCol="rawPrediction", metricName="areaUnderROC")
mc_evaluator_acc = MulticlassClassificationEvaluator(labelCol="label", predictionCol="prediction", metricName="accuracy")
mc_evaluator_f1  = MulticlassClassificationEvaluator(labelCol="label", predictionCol="prediction", metricName="f1")
mc_evaluator_prec = MulticlassClassificationEvaluator(labelCol="label", predictionCol="prediction", metricName="weightedPrecision")
mc_evaluator_rec  = MulticlassClassificationEvaluator(labelCol="label", predictionCol="prediction", metricName="weightedRecall")

def evaluate_classifier(preds, name):
    auc  = bin_evaluator.evaluate(preds)
    acc  = mc_evaluator_acc.evaluate(preds)
    f1   = mc_evaluator_f1.evaluate(preds)
    prec = mc_evaluator_prec.evaluate(preds)
    rec  = mc_evaluator_rec.evaluate(preds)
    print(f"\n=== {name} — Test Set Results ===")
    print(f"  Accuracy  : {acc:.4f}")
    print(f"  Precision : {prec:.4f}")
    print(f"  Recall    : {rec:.4f}")
    print(f"  F1 Score  : {f1:.4f}")
    print(f"  AUC-ROC   : {auc:.4f}")
    return {"Model": name, "Accuracy": acc, "Precision": prec, "Recall": rec, "F1": f1, "AUC-ROC": auc}

lr_clf_metrics = evaluate_classifier(log_reg_preds, "Logistic Regression")

print("\nSample Predictions:")
log_reg_preds.select("label", "prediction", "probability").show(10)

"""###  Confusion Matrix

"""

def confusion_matrix_spark(preds, model_name):
    """Compute and display confusion matrix from Spark predictions."""
    cm = preds.groupBy("label", "prediction").count().orderBy("label", "prediction").toPandas()
    print(f"\n=== Confusion Matrix — {model_name} ===")
    print(cm.to_string(index=False))
    return cm

lr_cm = confusion_matrix_spark(log_reg_preds, "Logistic Regression")

"""---
## 6. Visualizations

"""

# ── Plot 1: Actual vs Predicted Price (Linear Regression) ────────────────────
preds_pd = lr_preds.select("label", "prediction").sample(fraction=0.3, seed=42).toPandas()

plt.figure(figsize=(8, 6))
plt.scatter(preds_pd["label"], preds_pd["prediction"], alpha=0.4, edgecolors='none', color='steelblue', s=20)
max_val = max(preds_pd["label"].max(), preds_pd["prediction"].max())
plt.plot([0, max_val], [0, max_val], 'r--', linewidth=1.5, label="Perfect prediction")
plt.xlabel("Actual Price", fontsize=12)
plt.ylabel("Predicted Price", fontsize=12)
plt.title(f"Linear Regression\nActual vs Predicted Price  (R² = {lr_r2:.3f})", fontsize=13)
plt.legend()
plt.tight_layout()
plt.savefig("reg_actual_vs_predicted.png", dpi=150)
plt.show()

# ── Plot 2: Residuals Distribution ───────────────────────────────────────────
preds_pd["residual"] = preds_pd["label"] - preds_pd["prediction"]

plt.figure(figsize=(9, 5))
plt.hist(preds_pd["residual"], bins=60, color="steelblue", edgecolor="white", alpha=0.85)
plt.axvline(0, color="red", linestyle="--", linewidth=1.5, label="Zero residual")
plt.xlabel("Residual (Actual − Predicted)", fontsize=12)
plt.ylabel("Frequency", fontsize=12)
plt.title("Residual Distribution — Linear Regression", fontsize=13)
plt.legend()
plt.tight_layout()
plt.savefig("reg_residuals.png", dpi=150)
plt.show()

# ── Plot 3: Classification Metrics Bar Chart ──────────────────────────────────
metrics = {"Accuracy": lr_clf_metrics["Accuracy"], "Precision": lr_clf_metrics["Precision"],
           "Recall": lr_clf_metrics["Recall"], "F1": lr_clf_metrics["F1"], "AUC-ROC": lr_clf_metrics["AUC-ROC"]}

plt.figure(figsize=(8, 5))
bars = plt.bar(metrics.keys(), metrics.values(), color="darkorange", edgecolor="white")
plt.bar_label(bars, fmt="%.3f", padding=3, fontsize=10)
plt.ylim(0, 1.1)
plt.ylabel("Score", fontsize=12)
plt.title("Logistic Regression — Classification Metrics", fontsize=13)
plt.tight_layout()
plt.savefig("clf_metrics.png", dpi=150)
plt.show()

# ── Plot 4: Confusion Matrix Heatmap ─────────────────────────────────────────
import numpy as np

def cm_to_matrix(cm_pd):
    mat = np.zeros((2, 2), dtype=int)
    for _, row in cm_pd.iterrows():
        mat[int(row['label'])][int(row['prediction'])] += int(row['count'])
    return mat

mat = cm_to_matrix(lr_cm)
labels = ["Cart (0)", "Purchase (1)"]

plt.figure(figsize=(6, 5))
sns.heatmap(mat, annot=True, fmt='d', cmap='Blues',
            xticklabels=labels, yticklabels=labels, linewidths=0.5, cbar=False)
plt.title("Confusion Matrix — Logistic Regression", fontsize=13)
plt.xlabel("Predicted", fontsize=11)
plt.ylabel("Actual", fontsize=11)
plt.tight_layout()
plt.savefig("confusion_matrix.png", dpi=150)
plt.show()

# ── Plot 5: ROC Curve ─────────────────────────────────────────────────────────
roc_pd = lr_clf_summary.roc.toPandas()

plt.figure(figsize=(7, 6))
plt.plot(roc_pd["FPR"], roc_pd["TPR"], color='darkorange', lw=2,
         label=f"Logistic Regression (AUC = {lr_clf_metrics['AUC-ROC']:.3f})")
plt.plot([0, 1], [0, 1], 'k--', lw=1.2, label="Random classifier")
plt.xlabel("False Positive Rate", fontsize=12)
plt.ylabel("True Positive Rate", fontsize=12)
plt.title("ROC Curve — Logistic Regression", fontsize=13)
plt.legend(loc="lower right")
plt.tight_layout()
plt.savefig("roc_curve.png", dpi=150)
plt.show()

reg_results_df = pd.DataFrame([{
    "Model": "Linear Regression", "RMSE": lr_rmse, "MAE": lr_mae, "R2": lr_r2
}])
clf_results_df = pd.DataFrame([lr_clf_metrics])

reg_results_df.to_csv("regression_results.csv", index=False)
clf_results_df.to_csv("classification_results.csv", index=False)

"""---
# Association Rule Mining with Apriori (FP-Growth) in Apache Spark

This notebook applies association rule mining on an e-commerce dataset using **PySpark's FP-Growth**, which produces the same output as Apriori (frequent itemsets + association rules) but is optimized for distributed environments.

> **Dataset**: E-commerce event log (~135K rows) with columns: `event_type`, `product_id`, `brand`, `price`, `user_id`, `user_session`, `product_name`, `category`, `hour`, `day`, `month`, `year`

## Pipeline Overview
1. Initialize Spark Session
2. Load & Explore Data
3. Preprocess — build market baskets (transactions per user session)
4. Run FP-Growth (Apriori equivalent)
5. Explore Frequent Itemsets
6. Explore Association Rules
7. Filter & Interpret results
8. Visualize top rules
"""

# Distribution of event types
print("=== Event Type Distribution ===")
df.groupBy("event_type").count().orderBy(F.desc("count")).show()

# Unique counts
print("=== Unique Counts ===")
for col_name in ["user_id", "user_session", "product_id", "brand", "category"]:
    print(f"  {col_name:15s}: {df.select(col_name).distinct().count():,}")

# Options: 'product_name', 'brand', 'category'
ITEM_COLUMN = "product_name"

EVENT_FILTER = "purchase"   # or "cart" or None
MIN_BASKET_SIZE = 2

if EVENT_FILTER:
    events = df.filter(F.col("event_type") == EVENT_FILTER)
    print(f"Filtered to '{EVENT_FILTER}' events: {events.count():,} rows")
else:
    events = df
    print(f"Using all events: {events.count():,} rows")

events = events.dropna(subset=["user_session", ITEM_COLUMN])

#  Build baskets
baskets = (
    events
    .groupBy("user_session")
    .agg(F.collect_set(ITEM_COLUMN).alias("items"))
    .filter(F.size("items") >= MIN_BASKET_SIZE)
)

basket_count = baskets.count()
print(f"Total transactions (baskets) with >= {MIN_BASKET_SIZE} items: {basket_count:,}")
baskets.show(5, truncate=False)

# Basket size distribution
basket_sizes = baskets.withColumn("basket_size", F.size("items"))

print("=== Basket Size Distribution ===")
basket_sizes.groupBy("basket_size") \
    .count() \
    .orderBy("basket_size") \
    .show(20)

print("\n=== Basket Size Stats ===")
basket_sizes.select(
    F.min("basket_size").alias("min"),
    F.max("basket_size").alias("max"),
    F.avg("basket_size").alias("mean"),
    F.expr("percentile_approx(basket_size, 0.5)").alias("median")
).show()

"""## 4. Apply FP-Growth (Apriori Equivalent in Spark)

Spark MLlib provides **FP-Growth** which mines the same frequent itemsets and association rules as Apriori, but more efficiently via the FP-tree data structure.

Key parameters:
- **`minSupport`**: Minimum fraction of transactions that must contain an itemset for it to be considered frequent. e.g. `0.01` = must appear in at least 1% of sessions.
- **`minConfidence`**: Minimum confidence for an association rule. e.g. `0.3` = rule is correct 30% of the time its antecedent occurs.
"""

MIN_SUPPORT    = 0.01   # 1% of sessions — lower = more itemsets but slower
MIN_CONFIDENCE = 0.30   # 30% confidence threshold for rules
# ──────────────────────────────────────────────────────────────────────────────

fpgrowth = FPGrowth(
    itemsCol="items",
    minSupport=MIN_SUPPORT,
    minConfidence=MIN_CONFIDENCE
)

print(f"Running FP-Growth with minSupport={MIN_SUPPORT}, minConfidence={MIN_CONFIDENCE}...")
model = fpgrowth.fit(baskets)
print("Done!")

"""## 5. Frequent Itemsets"""

freq_itemsets = model.freqItemsets

total_itemsets = freq_itemsets.count()
print(f"Total frequent itemsets found: {total_itemsets:,}")

freq_itemsets = freq_itemsets \
    .withColumn("itemset_size", F.size("items")) \
    .withColumn("support", F.col("freq") / basket_count)

print("\n=== Frequent Itemsets by Size ===")
freq_itemsets.groupBy("itemset_size").count().orderBy("itemset_size").show()

print("\n=== Top 20 Most Frequent Itemsets ===")
freq_itemsets.orderBy(F.desc("freq")).show(20, truncate=False)

# Top single items (1-itemsets)
print("=== Top 15 Most Frequent Individual Items ===")
freq_itemsets \
    .filter(F.col("itemset_size") == 1) \
    .orderBy(F.desc("freq")) \
    .show(15, truncate=False)

# Top pairs (2-itemsets)
print("\n=== Top 15 Most Frequent Item Pairs ===")
freq_itemsets \
    .filter(F.col("itemset_size") == 2) \
    .orderBy(F.desc("freq")) \
    .show(15, truncate=False)

# Top triples (3-itemsets), if any
print("\n=== Top 10 Most Frequent Item Triples (3-itemsets) ===")
freq_itemsets \
    .filter(F.col("itemset_size") == 3) \
    .orderBy(F.desc("freq")) \
    .show(10, truncate=False)

"""## 6. Association Rules"""

rules = model.associationRules

total_rules = rules.count()
print(f"Total association rules found: {total_rules:,}")

print("\n=== Association Rules Schema ===")
rules.printSchema()

# antecedent  → consequent  [support, confidence, lift]
print("\n=== Sample Rules ===")
rules.show(10, truncate=False)

# support    = P(A ∩ B)  — how often A and B appear together
# confidence = P(B | A)  — given A, how often is B also bought?
# lift  = confidence / P(B) — > 1 means A and B are positively correlated


print("=== Top 20 Rules by Lift (Strongest Associations) ===")
rules \
    .orderBy(F.desc("lift")) \
    .show(20, truncate=False)

print("\n=== Top 20 Rules by Confidence ===")
rules \
    .orderBy(F.desc("confidence")) \
    .show(20, truncate=False)

# Rules summary statistics
print("=== Rule Metrics Summary ===")
rules.select(
    F.min("confidence").alias("conf_min"),
    F.max("confidence").alias("conf_max"),
    F.avg("confidence").alias("conf_avg"),
    F.min("lift").alias("lift_min"),
    F.max("lift").alias("lift_max"),
    F.avg("lift").alias("lift_avg"),
    F.min("support").alias("supp_min"),
    F.max("support").alias("supp_max"),
).show()

"""## 7. Filter & Refine Rules

Apply additional filters to keep only the most actionable rules.
"""

# lift > 1 (positive correlation) AND confidence >= 0.4
LIFT_THRESHOLD       = 1.0
CONFIDENCE_THRESHOLD = 0.40

strong_rules = rules.filter(
    (F.col("lift") > LIFT_THRESHOLD) &
    (F.col("confidence") >= CONFIDENCE_THRESHOLD)
)

print(f"Strong rules (lift > {LIFT_THRESHOLD}, confidence >= {CONFIDENCE_THRESHOLD}): {strong_rules.count()}")
strong_rules.orderBy(F.desc("lift")).show(20, truncate=False)

rules_pd = rules \
    .withColumn("antecedent_str", F.concat_ws(" + ", "antecedent")) \
    .withColumn("consequent_str", F.concat_ws(" + ", "consequent")) \
    .select("antecedent_str", "consequent_str", "support", "confidence", "lift") \
    .toPandas()

print(f"Rules collected to Pandas: {len(rules_pd)} rows")
rules_pd.sort_values("lift", ascending=False).head(10)

"""## 8. Visualizations"""

#  Support vs Confidence
plt.figure(figsize=(10, 6))
sc = plt.scatter(
    rules_pd["support"],
    rules_pd["confidence"],
    c=rules_pd["lift"],
    cmap="YlOrRd",
    alpha=0.7,
    edgecolors="grey",
    linewidths=0.3,
    s=60
)
plt.colorbar(sc, label="Lift")
plt.xlabel("Support", fontsize=12)
plt.ylabel("Confidence", fontsize=12)
plt.title("Association Rules — Support vs Confidence (colored by Lift)", fontsize=14)
plt.tight_layout()
plt.savefig("rules_scatter.png", dpi=150)
plt.show()
print("Saved: rules_scatter.png")

# Top 15 Rules by Lift horizontal bar chart
top15 = rules_pd.nlargest(15, "lift").copy()
top15["rule"] = top15["antecedent_str"] + "  →  " + top15["consequent_str"]

fig, ax = plt.subplots(figsize=(12, 7))
bars = ax.barh(top15["rule"], top15["lift"], color="steelblue", edgecolor="white")
ax.axvline(x=1, color="red", linestyle="--", linewidth=1.2, label="Lift = 1 (no association)")
ax.bar_label(bars, fmt="%.2f", padding=3, fontsize=9)
ax.set_xlabel("Lift", fontsize=12)
ax.set_title("Top 15 Association Rules by Lift", fontsize=14)
ax.invert_yaxis()
ax.legend()
plt.tight_layout()
plt.savefig("top15_rules_lift.png", dpi=150)
plt.show()
print("Saved: top15_rules_lift.png")

top15_conf = rules_pd.nlargest(15, "confidence").copy()
top15_conf["rule"] = top15_conf["antecedent_str"] + "  →  " + top15_conf["consequent_str"]

fig, ax = plt.subplots(figsize=(12, 7))
bars = ax.barh(top15_conf["rule"], top15_conf["confidence"], color="darkorange", edgecolor="white")
ax.bar_label(bars, fmt="%.2f", padding=3, fontsize=9)
ax.xaxis.set_major_formatter(mtick.PercentFormatter(xmax=1))
ax.set_xlabel("Confidence", fontsize=12)
ax.set_title("Top 15 Association Rules by Confidence", fontsize=14)
ax.invert_yaxis()
plt.tight_layout()
plt.savefig("top15_rules_confidence.png", dpi=150)
plt.show()
print("Saved: top15_rules_confidence.png")

# Frequent Itemsets
size_counts = freq_itemsets \
    .groupBy("itemset_size") \
    .count() \
    .orderBy("itemset_size") \
    .toPandas()

plt.figure(figsize=(8, 5))
plt.bar(size_counts["itemset_size"].astype(str), size_counts["count"], color="mediumseagreen")
plt.xlabel("Itemset Size (number of items)", fontsize=12)
plt.ylabel("Number of Frequent Itemsets", fontsize=12)
plt.title("Frequent Itemsets by Size", fontsize=14)
for i, row in size_counts.iterrows():
    plt.text(i, row["count"] + 0.5, str(row["count"]), ha="center", fontsize=11)
plt.tight_layout()
plt.savefig("itemset_size_distribution.png", dpi=150)
plt.show()
print("Saved: itemset_size_distribution.png")

"""## 9. Experiment: Mine at Category Level

Re-run the pipeline using `category` instead of `product_name` for coarser, more interpretable rules.
"""

# Build category-level baskets
cat_baskets = (
    events
    .dropna(subset=["user_session", "category"])
    .groupBy("user_session")
    .agg(F.collect_set("category").alias("items"))
    .filter(F.size("items") >= 2)
)

cat_count = cat_baskets.count()
print(f"Category-level transactions: {cat_count:,}")

# FP-Growth on categories with lower support (fewer unique categories → can lower threshold)
fp_cat = FPGrowth(itemsCol="items", minSupport=0.005, minConfidence=0.2)
model_cat = fp_cat.fit(cat_baskets)

print("\n=== Frequent Category Itemsets ===")
model_cat.freqItemsets \
    .withColumn("support", F.col("freq") / cat_count) \
    .orderBy(F.desc("freq")) \
    .show(20, truncate=False)

print("\n=== Category Association Rules (by Lift) ===")
model_cat.associationRules \
    .orderBy(F.desc("lift")) \
    .show(20, truncate=False)

"""## 10. Save Results"""

freq_itemsets_pd = freq_itemsets \
    .withColumn("items_str", F.concat_ws(" | ", "items")) \
    .select("items_str", "freq", "support", "itemset_size") \
    .toPandas()

freq_itemsets_pd.to_csv("frequent_itemsets.csv", index=False)
rules_pd.to_csv("association_rules.csv", index=False)

print(f"Saved {len(freq_itemsets_pd)} frequent itemsets → frequent_itemsets.csv")
print(f"Saved {len(rules_pd)} association rules   → association_rules.csv")

rules_pd.sort_values("lift", ascending=False).head(10)

spark.stop()